import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'

import { Button, createStyles, FileButton } from '@mantine/core'
import SliderContainer from '../components/SliderContainer'


const useStyle = createStyles(() => ({
  "main": {
    padding: "0",
    margin: "0",

    width: "100%",

    display: "grid",
    gridTemplateColumns: "1fr 25%",
    gridTemplateRows: "1fr",
    gap: "0px 0px",
    gridAutoFlow: "row",
    gridTemplateAreas:
      ". .",
    height: "100vh",
  },
  "ImageArea": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgb(14, 14, 70)",
    "p": {
      textAlign: "center"
    },
    "canvas": {
      maxHeight: "90vh",
      maxWidth: "90%",
    }
  },

  "SettingsPanel": {
    backgroundColor: "brown"
  },

  "Settings": {
    height: "max-content",
    padding: "1em"
  },


  "BottomButtons": {
    marginBottom: "0%",
    height: "auto",
  },

  "button": {
    width: "fit-content",
    margin: "1em",
    float: "inline-start",
  },

  "right": {
    float: "inline-end",
  },

  "SliderContainer": {
    margin: "0.5em",
    display: "flex",
    flexDirection: "column",
    height: "3em",
  },
  "Slider": {
    display: "grid",
    gridAutoColumns: "1fr",
    gridTemplateColumns: "1fr 2em 2em",
    gridTemplateRows: "1fr",
    gap: "0.2em 0.2em",
    gridTemplateAreas:
      ". . .",
    alignItems: "center",
  },
  "flexChild": {
    flex: "1"
  },
  "hidden": {
    display: "none"
  }

}))


export default function App() {

  const { classes } = useStyle()

  const [config, setConfig] = useState({
    brightness: 0,
    contrast: 0,
    saturation: 0
  })

  const canvasRef = useRef<HTMLCanvasElement>(null);
  const imgRef = useRef<HTMLImageElement>(null); 

  const [file, setFile] = useState(null)

  function handleFileSelect(e: any) {
    setFile(e)
  }

  function changeConfig(name: string, newValue: number) {
    setConfig(prevConfig => {
      return {
        ...prevConfig,
        [name]: newValue
      }
    })
  }

  useEffect(() => {
    if (file) {
      
      const reader = new FileReader()
      
      reader.onload = function (e) {
        const img = new Image();
        img.src = e.target?.result as string; 
        img.onload = function () {
          const canvas = canvasRef.current as HTMLCanvasElement;

          canvas.width = img.width;
          canvas.height = img.height;

          const ctx = canvas.getContext("2d");
          
          if(!ctx) return;

          ctx.filter = `brightness(${(config.brightness+100)/100})
                        contrast(${(config.contrast+100) / 100})
                        saturate(${config.saturation + 100}%)`

          ctx.drawImage(img, 0, 0);
        }

        if (!img.src) return
      }
      reader.readAsDataURL(file)
    }
  }, [file, config])


  return (
    <>
      <Head>
        <title>Image Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>

        {/* {CANVAS AREA} */}
        <div className={classes.ImageArea}>
          <canvas ref={canvasRef} width={500} height={500}></canvas>
          <img ref={imgRef} className={classes.hidden} />
        </div>


        <div className={classes.SettingsPanel}>
          <div className={classes.Settings}>
            <SliderContainer value={config.brightness} changeConfig={changeConfig} name="brightness" label="Brightness" />
            <SliderContainer value={config.contrast} changeConfig={changeConfig} name="contrast" label="Contrast" />
            <SliderContainer value={config.saturation} changeConfig={changeConfig} name="saturation" label="Saturation" />
          </div>

          <div className={classes.BottomButtons}>
            <FileButton onChange={handleFileSelect} accept="image/png,image/jpeg">
              {(props) => <Button className={classes.button} {...props}>Open</Button>}
            </FileButton>
            <Button className={`${classes.button} ${classes.right}`}>
              Save
            </Button>
            <Button className={`${classes.button} ${classes.right}`}>
              Save As
            </Button>
          </div>
        </div>
      </main>
    </>
  )
}