import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Index.module.css'
import { useState, useEffect, use } from 'react'

import SettingsPanel from '../components/SettingsPanel'
import ImageArea from '../components/ImageArea'
import { Button } from '@mantine/core'
import { setRevalidateHeaders } from 'next/dist/server/send-payload'

const inter = Inter({ subsets: ['latin'] })

export default function App() {

  const [config, setConfig] = useState({
    brightness: 0,
    contrast: 0
  })

  useEffect(() => {
    console.log(config); // log the updated state value after it has been set
  }, [config]);


  function changeConfig(name, newValue) {
    // WE ARE GETTING THE VALUE HERE, BUT IT'S NOT UPDATING IN STATE
    setConfig(prevConfig => {
      return {
        ...prevConfig,
        [name]: newValue
      };
    });
    
    
  }


  // console.log("update")
  return (
    <>
      <Head>
        <title>Image Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {/* <Button name="hello" onClick={changeConfig}>Increment Brightness</Button> */}
        <ImageArea className={styles.imageArea} />
        <SettingsPanel config={config} changeConfig={changeConfig} className={styles.settingsPanel} />
      </main>
    </>
  )
}